# Generated by Django 3.2.4 on 2021-07-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='value',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
    ]
