# Generated by Django 3.2.4 on 2021-07-18 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flags', '0003_featureflag_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
