# Generated by Django 3.2.5 on 2021-07-18 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('eula', models.TextField()),
                ('privacy_polivy', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('version', models.AutoField(primary_key=True, serialize=False)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('eula_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
