# Generated by Django 3.2.5 on 2021-07-18 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal', '0003_rename_privacy_polivy_policy_privacy_policy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLog',
            new_name='PolicyLog',
        ),
    ]
