# Generated by Django 3.2.4 on 2021-06-24 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DragRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('race_type', models.CharField(choices=[('standard', 'standard'), ('all star', 'all star')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('drag_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.dragrace')),
            ],
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('point_value', models.IntegerField(default=1)),
                ('drag_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.dragrace')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.episode')),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.queen')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.rule')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('drag_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.dragrace')),
                ('participants', models.ManyToManyField(to='fantasydrag.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='dragrace',
            name='queens',
            field=models.ManyToManyField(to='fantasydrag.Queen'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.panel')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.participant')),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.queen')),
            ],
        ),
    ]
