# Generated by Django 3.2.4 on 2021-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0004_dragrace_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='queen_draft_allowance',
            field=models.IntegerField(default=1),
        ),
    ]
