# Generated by Django 3.2.4 on 2021-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0005_panel_queen_draft_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='draft_order',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='panel',
            name='queen_draft_allowance',
            field=models.IntegerField(default=1, help_text='The number of times a Queen can be drafted to a unique player'),
        ),
    ]
