# Generated by Django 3.2.4 on 2021-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0007_auto_20210624_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='round_selected',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='panel',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
