# Generated by Django 3.2.4 on 2021-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0008_auto_20210624_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='force_even_teams',
            field=models.BooleanField(default=False, help_text='When randomly assigning drafts, this forces teams to be evenly numbered when\n        queens/participants is not a whole number'),
        ),
    ]
