# Generated by Django 3.2.4 on 2021-06-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0009_panel_force_even_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='force_even_teams',
        ),
    ]
