# Generated by Django 3.2.4 on 2021-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0010_remove_panel_force_even_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('point_value', 'name')},
        ),
        migrations.AddField(
            model_name='panel',
            name='captains',
            field=models.ManyToManyField(related_name='panelcaptains', to='fantasydrag.Participant'),
        ),
    ]
