# Generated by Django 3.2.4 on 2021-06-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0011_auto_20210625_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='site_admin',
            field=models.BooleanField(default=False),
        ),
    ]
