# Generated by Django 3.2.4 on 2021-06-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0012_participant_site_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='episodes',
            field=models.ManyToManyField(to='fantasydrag.Episode'),
        ),
    ]
