# Generated by Django 3.2.4 on 2021-06-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0013_participant_episodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('number',)},
        ),
        migrations.AddField(
            model_name='episode',
            name='is_scored',
            field=models.BooleanField(default=False),
        ),
    ]
