# Generated by Django 3.2.4 on 2021-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0017_auto_20210627_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
