# Generated by Django 3.2.4 on 2021-06-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0018_episode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcardappearance',
            name='appearance_type',
            field=models.CharField(choices=[('Flashback', 'Flashback'), ('IRL', 'IRL'), ('Lipsync Assassin', 'Lipsync Assassin')], default='IRL', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildcardappearance',
            name='point_value',
            field=models.IntegerField(default=1),
        ),
    ]
