# Generated by Django 3.2.4 on 2021-06-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0019_auto_20210627_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='episodes',
            field=models.ManyToManyField(blank=True, null=True, to='fantasydrag.Episode'),
        ),
    ]
