# Generated by Django 3.2.4 on 2021-06-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0021_auto_20210629_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='wildcardappearance',
            name='appearance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasydrag.appearancetype'),
        ),
    ]
