# Generated by Django 3.2.4 on 2021-07-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0022_auto_20210629_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together={('panel', 'participant', 'queen')},
        ),
    ]
