# Generated by Django 3.2.4 on 2021-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0023_auto_20210701_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='force_equal_teams',
            field=models.BooleanField(default=False),
        ),
    ]
