# Generated by Django 3.2.4 on 2021-07-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0024_panel_force_equal_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='force_equal_teams',
            new_name='force_even_teams',
        ),
    ]
