# Generated by Django 3.2.4 on 2021-07-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0025_rename_force_equal_teams_panel_force_even_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='force_even_teams',
        ),
        migrations.AddField(
            model_name='panel',
            name='team_size',
            field=models.IntegerField(default=1, help_text='The number of drafts per team'),
        ),
    ]
