# Generated by Django 3.2.4 on 2021-07-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0026_auto_20210701_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='draft_type',
            field=models.CharField(choices=[('byTeamSize', 'byTeamSize'), ('byQueenCount', 'byQueenCount')], default='byQueenCount', max_length=25),
            preserve_default=False,
        ),
    ]
