# Generated by Django 3.2.4 on 2021-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0028_panel_draft_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='draft_rules',
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
