# Generated by Django 3.2.4 on 2021-07-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0030_rename_name_participant_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='normalized_display_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
