# Generated by Django 3.2.4 on 2021-07-05 21:47

from django.db import migrations


def forwards(apps, schema_editor):
    from fantasydrag.models import Participant

    for participant in Participant.objects.all():
        participant.normalized_display_name = participant.display_name.lower()
        participant.save()


def backwards(apps, schema_editor):
    from fantasydrag.models import Participant

    for participant in Participant.objects.all():
        participant.normalized_display_name = None
        participant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0031_participant_normalized_display_name'),
    ]

    operations = [migrations.RunPython(forwards, backwards), ]
