# Generated by Django 3.2.4 on 2021-07-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0032_custom_set_normalized_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='normalized_display_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
