# Generated by Django 3.2.4 on 2021-07-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0033_alter_participant_normalized_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dragrace',
            unique_together={('season', 'race_type', 'franchise')},
        ),
    ]
