# Generated by Django 3.2.4 on 2021-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0034_alter_dragrace_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('point_value', models.IntegerField(default=1)),
                ('score_type', models.CharField(choices=[('episode', 'episode'), ('season', 'season')], max_length=10)),
            ],
            options={
                'ordering': ('score_type', 'point_value', 'name'),
                'abstract': False,
            },
        ),
    ]
