# Generated by Django 3.2.4 on 2021-07-06 10:49

from django.db import migrations


def forwards(apps, schema_editor):
    pass


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0035_defaultrule'),
    ]

    operations = [migrations.RunPython(forwards, backwards), ]
