# Generated by Django 3.2.4 on 2021-07-06 10:49

from django.db import migrations
from fantasydrag.models import DefaultRule, Rule


def forwards(apps, schema_editor):
    existing_rules = Rule.objects.all()
    for rule in existing_rules:
        default_rule = DefaultRule(
            name=rule.name,
            description=rule.description,
            point_value=rule.point_value,
            score_type=rule.score_type
        )
        default_rule.save()


def backwards(apps, schema_editor):
    DefaultRule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0035_defaultrule'),
    ]

    operations = [migrations.RunPython(forwards, backwards), ]
