# Generated by Django 3.2.4 on 2021-07-12 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0039_panel_wildcard_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in draft', 'in draft'), ('active', 'active'), ('wildcards', 'wildcards'), ('closed', 'closed')], default='open', max_length=25),
        ),
    ]
