# Generated by Django 3.2.4 on 2021-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0040_auto_20210712_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='normalized_name',
            field=models.CharField(default='teamporkchop', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
