# Generated by Django 3.2.4 on 2021-07-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0042_dragrace_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='queen_draft_allowance',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='team_size',
        ),
        migrations.AddField(
            model_name='panel',
            name='draft_variable',
            field=models.IntegerField(default=1, help_text='The number of times a Queen can be drafted to a unique player or the number of drafts per team'),
        ),
    ]
