# Generated by Django 3.2.4 on 2021-07-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0047_alter_panel_panel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='draft_variable',
        ),
        migrations.AddField(
            model_name='panel',
            name='draft_rules',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
