# Generated by Django 3.2.4 on 2021-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0049_auto_20210714_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='participant_drafts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
