# Generated by Django 3.2.4 on 2021-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0050_panel_participant_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='current_participant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panel',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
