# Generated by Django 3.2.4 on 2021-07-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0051_auto_20210714_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='draft_data',
        ),
    ]
