# Generated by Django 3.2.4 on 2021-07-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0052_remove_panel_draft_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='draft_rules',
        ),
    ]
