# Generated by Django 3.2.4 on 2021-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0055_dragrace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='main_franchise',
            field=models.CharField(choices=[('US', 'US'), ('Down Under', 'Down Under'), ('UK', 'UK'), ('Canada', 'Canada')], default='US', max_length=100),
        ),
    ]
