# Generated by Django 3.2.4 on 2021-07-16 09:12

from django.db import migrations
from fantasydrag.models import Rule, DefaultRule


def forwards(apps, schema_editor):
    models = [Rule, DefaultRule]
    season_rules = [
        'Season Top 4',
        "RuPaul's Best Friend Race",
        'Season Runner Up',
        'Prance, My Queen!',
        'Reading is Fundamental',
        'Snatched for the Gods'
    ]
    for model in models:
        model.objects.all().update(score_type='episode')
        model.objects.filter(name__in=season_rules).update(score_type='season')


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0056_queen_main_franchise'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
