# Generated by Django 3.2.4 on 2021-07-16 09:12

from django.db import migrations


def forwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0056_queen_main_franchise'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
