# Generated by Django 3.2.4 on 2021-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0058_auto_20210716_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='score_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='queen',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
