# Generated by Django 3.2.4 on 2021-07-16 10:43

from django.db import migrations
from fantasydrag.models import Queen


def forwards(apps, schema_editor):
    queens = Queen.objects.all()
    for queen in queens:
        queen.save()


def reverse(apps, schema_editor):
    queens = Queen.objects.update(normalized_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0061_auto_20210716_1043'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
