# Generated by Django 3.2.4 on 2021-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0062_populate_queen_normalized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queen',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
    ]
