# Generated by Django 3.2.4 on 2021-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0065_auto_20210716_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultrule',
            name='drag_race_type',
            field=models.CharField(choices=[('standard', 'standard'), ('international', 'international'), ('all star', 'all star')], db_index=True, default='standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='drag_race_type',
            field=models.CharField(choices=[('standard', 'standard'), ('international', 'international'), ('all star', 'all star')], db_index=True, default='standard', max_length=100),
        ),
    ]
