# Generated by Django 3.2.4 on 2021-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0066_auto_20210716_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragRaceType',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
    ]
