# Generated by Django 3.2.4 on 2021-07-16 11:28

from django.db import migrations
from fantasydrag.models import DragRaceType


def forwards(apps, schema_editor):
    types = [
        'standard', 'all star', 'international'
    ]
    for _type in types:
        drt = DragRaceType(name=_type)
        drt.save()


def reverse(apps, schema_editor):
    DragRaceType.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0067_dragracetype'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
