# Generated by Django 3.2.4 on 2021-07-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0069_alter_dragrace_race_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragrace',
            old_name='race_type',
            new_name='drag_race_type',
        ),
        migrations.AlterUniqueTogether(
            name='dragrace',
            unique_together={('season', 'drag_race_type', 'franchise')},
        ),
    ]
