# Generated by Django 3.2.4 on 2021-07-16 11:40

from django.db import migrations
from fantasydrag.models import Score, DefaultRule


def forwards(apps, schema_editor):
    for score in Score.objects.all():
        try:
            score.default_rule = DefaultRule.objects.get(name=score.rule.name)
        except DefaultRule.DoesNotExist:
            dr = DefaultRule(
                name=score.rule.name,
                point_value=score.rule.point_value,
                description=score.rule.description,
                drag_race_type=score.rule.drag_race_type
            )
            dr.save()
            score.default_rule = dr
        score.save()


def reverse(apps, schema_editor):
    Score.objects.all().update(default_rule=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0072_score_default_rule'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
