# Generated by Django 3.2.4 on 2021-07-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0073_rejig_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='rule',
        ),
        migrations.AlterField(
            model_name='score',
            name='default_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.defaultrule'),
        ),
    ]
