# Generated by Django 3.2.4 on 2021-07-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0074_auto_20210716_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='default_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.defaultrule'),
        ),
    ]
