# Generated by Django 3.2.4 on 2021-07-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0075_alter_score_default_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultrule',
            old_name='drag_race_type',
            new_name='drag_race_types',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='drag_race_type',
            new_name='drag_race_types',
        ),
    ]
