# Generated by Django 3.2.4 on 2021-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0076_auto_20210716_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultrule',
            name='drag_race_types',
        ),
        migrations.AddField(
            model_name='defaultrule',
            name='drag_race_types',
            field=models.ManyToManyField(to='fantasydrag.DragRaceType'),
        ),
        migrations.RemoveField(
            model_name='rule',
            name='drag_race_types',
        ),
        migrations.AddField(
            model_name='rule',
            name='drag_race_types',
            field=models.ManyToManyField(to='fantasydrag.DragRaceType'),
        ),
    ]
