# Generated by Django 3.2.4 on 2021-07-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0079_auto_20210717_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drag_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.dragrace')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasydrag.participant')),
                ('queens', models.ManyToManyField(to='fantasydrag.Queen')),
            ],
            options={
                'unique_together': {('drag_race', 'participant')},
            },
        ),
    ]
