# Generated by Django 3.2.4 on 2021-07-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0080_generalpanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dragrace',
            name='open_for_panels',
        ),
    ]
