# Generated by Django 3.2.4 on 2021-07-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0081_remove_dragrace_open_for_panels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragrace',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='dragrace',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('active', 'active'), ('closed', 'closed'), ('pending', 'pending')], db_index=True, default='open', max_length=25),
        ),
    ]
