# Generated by Django 3.2.4 on 2021-07-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0082_auto_20210717_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeQueens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.episode')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasydrag.participant')),
                ('queens', models.ManyToManyField(to='fantasydrag.Queen')),
            ],
            options={
                'unique_together': {('episode', 'participant')},
            },
        ),
    ]
