# Generated by Django 3.2.4 on 2021-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0083_episodequeens'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='has_aired',
            field=models.BooleanField(default=True),
        ),
    ]
