# Generated by Django 3.2.4 on 2021-07-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0086_auto_20210718_0907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EpisodeQueens',
            new_name='EpisodeDraft',
        ),
    ]
