# Generated by Django 3.2.4 on 2021-07-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0087_rename_episodequeens_episodedraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralPanel',
        ),
    ]
