# Generated by Django 3.2.4 on 2021-07-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0088_delete_generalpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('cummulative_dragrace_drafts', 'cummulative_dragrace_drafts')], db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('drag_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasydrag.dragrace')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.participant')),
            ],
        ),
    ]
