# Generated by Django 3.2.4 on 2021-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0089_participantstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantstats',
            name='primary_stat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
