# Generated by Django 3.2.4 on 2021-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0090_participantstats_primary_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('in draft', 'in draft'), ('active', 'active'), ('wildcards', 'wildcards'), ('closed', 'closed')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='participantstats',
            name='stat_type',
            field=models.CharField(choices=[('cummulative_dragrace_drafts', 'cummulative_dragrace_drafts'), ('dragrace_rank', 'dragrace_rank')], db_index=True, max_length=100),
        ),
    ]
