# Generated by Django 3.2.5 on 2021-07-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0092_auto_20210718_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.panel'),
        ),
    ]
