# Generated by Django 3.2.5 on 2021-07-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0093_stats_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='normalized_display_name',
        ),
    ]
