# Generated by Django 3.2.5 on 2021-07-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0095_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='queen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.queen'),
        ),
    ]
