# Generated by Django 3.2.5 on 2021-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0097_auto_20210718_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='primary_stat',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stat_type',
            field=models.CharField(choices=[('cummulative_dragrace_drafts', 'cummulative_dragrace_drafts'), ('dragrace_rank', 'dragrace_rank'), ('dragrace_panel_scores', 'dragrace_panel_scores'), ('participant_queen_scores', 'participant_queen_scores'), ('dragrace_queen_scores', 'dragrace_queen_scores'), ('queen_scores', 'queen_scores')], db_index=True, max_length=100),
        ),
    ]
