# Generated by Django 3.2.5 on 2021-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0098_auto_20210719_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragrace',
            name='premier_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stat_type',
            field=models.CharField(choices=[('cummulative_dragrace_drafts', 'cummulative_dragrace_drafts'), ('dragrace_rank', 'dragrace_rank'), ('dragrace_panel_scores', 'dragrace_panel_scores'), ('participant_queen_scores', 'participant_queen_scores'), ('participant_wildqueen_scores', 'participant_wildqueen_scores'), ('dragrace_queen_scores', 'dragrace_queen_scores'), ('queen_scores', 'queen_scores')], db_index=True, max_length=100),
        ),
    ]
