# Generated by Django 3.2.5 on 2021-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0099_auto_20210721_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='draft_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
