# Generated by Django 3.2.5 on 2021-07-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0100_panel_draft_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodedraft',
            name='rank_tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episodedraft',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episodedraft',
            name='total_participants',
            field=models.IntegerField(default=0),
        ),
    ]
