# Generated by Django 3.2.5 on 2021-07-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0101_auto_20210727_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragrace',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('active', 'active'), ('closed', 'closed'), ('archived', 'archived')], db_index=True, default='open', max_length=25),
        ),
    ]
