# Generated by Django 3.2.5 on 2021-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0103_alter_dragrace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrule',
            name='score_class',
            field=models.CharField(blank=True, choices=[('elimination', 'elimination'), ('lipsync_win', 'lipsync_win'), ('stay', 'stay'), ('main_win', 'main_win'), ('mini_win', 'mini_win'), ('safe', 'safe'), ('champion', 'champion'), ('runnerup', 'runnerup'), ('misscongeniality', 'misscongeniality')], db_index=True, max_length=25, null=True),
        ),
    ]
