# Generated by Django 3.2.5 on 2021-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0104_defaultrule_score_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
