# Generated by Django 3.2.5 on 2021-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0105_scoreclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrule',
            name='score_classes',
            field=models.ManyToManyField(to='fantasydrag.ScoreClass'),
        ),
    ]
