# Generated by Django 3.2.5 on 2021-08-01 13:37

from django.db import migrations
from fantasydrag.models import DefaultRule, ScoreClass


def forwards(apps, schema_editor):
    for rule in DefaultRule.objects.filter(score_class__isnull=False):
        score_class = ScoreClass.objects.get(name=rule.score_class)
        rule.score_classes.add(score_class)
        rule.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0107_manual_pop_scoreclasses'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
