# Generated by Django 3.2.5 on 2021-08-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0109_episodedraft_drag_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodedraft',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.episode'),
        ),
        migrations.AlterField(
            model_name='episodedraft',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasydrag.participant'),
        ),
        migrations.AlterField(
            model_name='episodedraft',
            name='queens',
            field=models.ManyToManyField(blank=True, to='fantasydrag.Queen'),
        ),
    ]
