# Generated by Django 3.2.5 on 2021-08-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0110_auto_20210803_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodedraft',
            name='rank_tier',
        ),
        migrations.RemoveField(
            model_name='episodedraft',
            name='score',
        ),
        migrations.RemoveField(
            model_name='episodedraft',
            name='total_participants',
        ),
    ]
