# Generated by Django 3.2.5 on 2021-07-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0100_panel_draft_time'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelistdragracescore',
            name='drag_race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.dragrace'),
            preserve_default=False,
        ),
    ]
