# Generated by Django 3.2.5 on 2021-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20210727_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelistdragracescore',
            name='total_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='panelistepisodescore',
            name='total_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
