# Generated by Django 3.2.5 on 2021-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20210728_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelistdragracescore',
            name='total_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='panelistepisodescore',
            name='total_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
