# Generated by Django 3.2.5 on 2021-08-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0103_alter_dragrace_status'),
        ('stats', '0007_auto_20210728_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeDraftScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('rank_tier', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('episodedraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.episodedraft')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_draftscore_target_participant', to='fantasydrag.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DragRaceDraftScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('rank_tier', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('drag_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasydrag.dragrace')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragrace_draftscore_target_participant', to='fantasydrag.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
