# Generated by Django 3.2.5 on 2021-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20210801_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalqueendragracescore',
            name='bottom_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queendragracescore',
            name='bottom_count',
            field=models.IntegerField(default=0),
        ),
    ]
