# Generated by Django 3.2.5 on 2021-08-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasydrag', '0111_auto_20210803_1349'),
        ('stats', '0010_auto_20210801_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DragRaceDraftScores',
            new_name='DragRaceDraftScore',
        ),
        migrations.RenameModel(
            old_name='EpisodeDraftScores',
            new_name='EpisodeDraftScore',
        ),
    ]
