# Generated by Django 3.2.5 on 2021-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20210803_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragracedraftscore',
            name='total_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='episodedraftscore',
            name='total_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
