# Generated by Django 3.2.5 on 2021-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagecenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('action', 'action needed'), ('resolved', 'resolved')], default='new', max_length=100),
        ),
    ]
