# Generated by Django 3.2.5 on 2021-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagecenter', '0002_contactmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='dispute_type',
            field=models.CharField(blank=True, choices=[('wrong', 'A score is wrong'), ('missing', 'A score is missing')], max_length=100, null=True),
        ),
    ]
